version: '3.8'

services:
  symfony_app:
    build:
      dockerfile: .docker/symfony/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:password@database:5432/symfony"
    networks:
      - symfony_network
  composer:
    build:
      dockerfile: .docker/composer/Dockerfile
    volumes:
      - ./src:/app
    networks:
      - symfony_network

networks:
  symfony_network:
    external: true
