version: '3.8'

services:
  symfony_app:
    build:
      context: .
      dockerfile: .docker/symfony/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    environment:
      DATABASE_URL: "postgres://user:password@database:5432/symfony"
    networks:
      - symfony_network

networks:
  symfony_network:
    external: true
